on: push
name: Deploy Flask App
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOSTNAME }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          local_path: ./*
          remote_path: app/python/flask/traffic-bulanan-yura
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SFTP_HOSTNAME }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/app/python/flask/traffic-bulanan-yura
            rm -rf .venv
            python3 -m venv .venv
            source .venv/bin/activate
            python3 -m pip install -r requirements.txt
